export const actionType = {
  CONTACT_POPUP: "CONTACT_POPUP",
  LOGIN_POPUP: "LOGIN_POPUP",
  REGISTER_POPUP: "REGISTER_POPUP",
  AVAILABILITY: "AVAILABILITY",
  STORAGE: "STORAGE",
  EQUIPMENT: "EQUIPMENT",
  CONFIRMATION: "CONFIRMATION",
  BASIC: "BASIC",
  KITCHEN_DATA: "KITCHEN_DATA",
  PROFILE: "PROFILE",
  FAVORITES: "FAVORITES",
  KITCHEN: "KITCHEN",
  ADDKITCHENDATA: "ADDKITCHENDATA",
  IS_REGISTER: "IS_REGISTER",
  IS_SEARCH: "IS_SEARCH",
  PREVIEW_KITCHEN: "PREVIEW_KITCHEN",
  USER_DETAILS: "USER_DETAILS"
};

export default actionType;
